version: "3.1"


services:
  db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "127.0.0.1:5434:5432"

  app:
    build: .
    command: mvn flyway:clean tomcat7:run -Deperusteet-ylops.devdb.user=test -Deperusteet-ylops.devdb.password=test -Deperusteet-ylops.devdb.jdbcurl="jdbc:postgresql://db/test" -Dspring.profiles.active=e2e
    environment:
      EPERUSTEET_YLOPS_USER: test
      EPERUSTEET_YLOPS_PASSWORD: test
      EPERUSTEET_YLOPS_JDBCURL: jdbc:postgresql://db/test
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - "db"
    links:
      - "db:db"
    volumes:
      - "$HOME/oph-configuration:/root/oph-configuration"

  e2e:
    environment:
      NODE_ENV: e2e
    image: cypress/base:10
    command: npm run dctests
    working_dir: "/app"
    depends_on:
      - "app"
    links:
      - "app:app"
    volumes:
      - ".:/app"
      - "/tmp/dccache:/root/.cache"
